[tool.poetry]
name = "BeginnerPy"
version = "2020.2.4"
description = ""
authors = ["Zech Zimmerman <hi@beginnerpy.com>"]

[tool.poetry.dependencies]
python = "^3.7.0"
colorama = "^0.4.3"
toml = "^0.10.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
