[package]
name    = "simplaz"
version = "0.1.0"
authors = ["Hugo Ledoux <h.ledoux@tudelft.nl>"]
license = "MIT"
homepage="https://github.com/hugoledoux/simplaz"
repository="https://github.com/hugoledoux/simplaz"
# documentation="https://github.com/hugoledoux/startin_python"
description = "A simple Python package to read LAZ files (LAS too)."
edition = "2018"


[dependencies]
las = { version = "0.7.1", features = ["laz"] }


[dependencies.pyo3]
version = "0.11"
features = ["extension-module"]


[lib]
name = "simplaz"
crate-type = ["cdylib"]


[package.metadata.maturin]
requires-dist = ["toml==0.10.0"]
classifier=["License :: OSI Approved :: MIT License"]