[tool.poetry]
name = "asypinner"
version = "0.1.0"
description = "Async command-line spinner"
authors = ["Hiroki Konishi <relastle@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
colorama = "^0.4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
