tsana_app_name: demo_modeless
tsana_api_key: 335cbcd9-b141-4e5a-9b88-d1283a9a0e3f
tsana_api_endpoint: https://stock-exp2-api.azurewebsites.net
series_limit: 5000000
models_in_training_limit_per_instance: 1
az_storage_account: tsana
az_storage_account_key: 
az_tsana_meta_table: modelmetaplugintest
az_tsana_result_table: modelresult
az_tsana_moniter_table: moniter
az_tsana_model_blob_connection: 
model_temp_dir: temp
model_data_dir: data
training_owner_life: 60
#lstm:
#  num_hidden: 32
#  batch_size: 50
#  validation_ratio: 0.3
#  validation_freq: 2
#  steps_per_epoc: 100
#  train_history_step: 730
#  epoc: 3