language: python
python:
    - "3.8"
install: pip install coverage coveralls flake8 mccabe mypy pylint pytest
script:
    - flake8 forecastvh
    - pylint forecastvh --exit-zero
    - mypy forecastvh
    - coverage erase
    - coverage run --include=forecastvh/* -m pytest -ra
    - coveralls